import type { Metadata } from "next";
import { Inter, Roboto, Rubik } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });
const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={rubik.className}>{children}</body>

    </html>
  );
}
